
import React from 'react';
import ArticleTemplate, { ArticleSection } from './ArticleTemplate';
import { Language } from '../types';

const ArticleAIRevolution: React.FC<{ language: Language, onBack: () => void }> = ({ language, onBack }) => {
  const isEn = language === 'en';

  const sections: ArticleSection[] = isEn ? [
    { type: 'paragraph', text: "In the product design and UX field, the influence of generative AI goes far beyond generating a few moodboards in Midjourney. It is fundamentally changing how we build digital products, forcefully pulling the designer's focus from the 'visual surface' up to the 'product logic layer'." },
    { type: 'heading', text: "1. Paradigm Shift: From Static UI to Generative UI" },
    { type: 'paragraph', text: "In the past, UX designers delivered static pages (Mockups). We predicted all user paths and drew fixed interfaces for every state. AI is introducing a new possibility: Generative UI." },
    { type: 'bullet', text: "On-demand generation: Future interfaces may not be pre-drawn but dynamically generated by AI based on real-time Intent and contextual data." },
    { type: 'bullet', text: "Challenge for designers: Our job is no longer to draw specific pages, but to define 'generation rules' and 'Constraints'. Designers need to design the 'personality' and 'boundaries' of the system." },
    { type: 'heading', text: "2. Workflow Reconstruction: Blurring Design and Product Boundaries" },
    { type: 'paragraph', text: "For professionals transitioning from UI to more upstream roles like Product Managers, AI is the strongest catalyst." },
    { type: 'bullet', text: "Collapse of Lo-fi to Hi-fi: Previously, moving from Wireframe to Hi-fi took days. Now, using AI tools like Figma plugins, sketches or text descriptions can be instantly converted into high-fidelity prototypes." },
    { type: 'bullet', text: "Impact: This means the cost of 'validating ideas' approaches zero. Designers can test成品-like prototypes at the very early stages of product definition." },
    { type: 'heading', text: "3. Ending the Drudgery: Automation of Systems and Docs" },
    { type: 'paragraph', text: "Any senior designer knows that maintaining Design Systems and writing Hand-off Specs are massive, boring time sinks. AI can analyze your design files, automatically generate annotations, component variant descriptions, and even directly output front-end usable Token code." },
    { type: 'heading', text: "4. Evolution of Core Competency: System Thinking" },
    { type: 'paragraph', text: "In the AI era, simply being good at the 'Pen Tool' or lighting rendering will no longer be a core moat. New core competencies for UX designers include:" },
    { type: 'bullet', text: "Abstraction and Modeling: Can you transform complex business logic into a clear information architecture?" },
    { type: 'bullet', text: "Prompt Engineering and Model Tuning: Can you precisely control AI outputs with natural language?" },
    { type: 'quote', text: "The future UX designer is essentially a product architect who understands visual language." },
    { type: 'heading', text: "Conclusion: Designers as Product Architects" },
    { type: 'paragraph', text: "AI is not here to steal jobs; it's here to 'de-noise'. it removes the noise generated by tool limitations—aligning pixels, cutting assets—forcing you to face the most essential questions: Who does this solve a problem for? Is the solution elegant enough?" }
  ] : [
    { type: 'paragraph', text: "在产品设计和 UX 领域，生成式 AI 的影响远不止于 Midjourney 生成几张情绪板。它正在从底层改变我们构建数字产品的方式，将设计师的关注点从“界面表现层”强行拉升至“产品逻辑层”。" },
    { type: 'heading', text: "1. 设计范式的转移：从 Static UI 到 Generative UI" },
    { type: 'paragraph', text: "过去，UX 设计师交付的是静态的页面（Mockups）。我们预测用户的所有路径，并为每一个状态画出固定的界面。AI 正在引入一种新的可能性：生成式界面（Generative UI）。" },
    { type: 'bullet', text: "按需生成： 未来的界面可能不是预先画好的，而是 AI 根据用户的实时意图（Intent）和上下文数据，动态生成最适合当前任务的组件。" },
    { type: 'bullet', text: "对设计师的挑战： 我们的工作不再是绘制每一个具体的页面，而是定义“生成规则”和“约束条件（Constraints）”。" },
    { type: 'heading', text: "2. 工作流的重构：模糊设计与产品的边界" },
    { type: 'paragraph', text: "对于正在从 UI 转型为更上游（如产品经理）角色的专业人士来说，AI 是最强的催化剂。" },
    { type: 'bullet', text: "低保真到高保真的坍缩： 以前，从线框图（Wireframe）到高保真设计图（Hi-fi）需要数天。现在，可以将手绘草图或简单的文本描述瞬间转化为可交互的高保真原型。" },
    { type: 'bullet', text: "影响： 这意味着“验证想法”的成本趋近于零。设计师可以在产品定义的早期阶段，就拿出接近成品的原型进行测试。" },
    { type: 'heading', text: "3. 枯燥工作的终结：设计系统与文档自动化" },
    { type: 'paragraph', text: "所有资深 UI/UX 设计师都知道，维护设计系统（Design System）和编写交付文档是巨大且枯燥的时间黑洞。AI 可以自动生成标注、组件变体说明，甚至直接输出前端可用的 Token 代码。" },
    { type: 'heading', text: "4. 核心竞争力的演变：系统思维 (System Thinking)" },
    { type: 'paragraph', text: "在 AI 时代，单纯擅长使用 Figma 的“钢笔工具”将不再是核心护城河。UX 设计师的新核心竞争力变为：" },
    { type: 'bullet', text: "抽象与建模能力： 能否将复杂的业务逻辑转化为清晰的信息架构？" },
    { type: 'bullet', text: "提示词工程与模型调优： 能否用自然语言精准控制 AI 工具输出符合设计规范的结果？" },
    { type: 'quote', text: "未来的 UX 设计师，实质上就是懂视觉语言的产品架构师。" },
    { type: 'heading', text: "结语：设计师即产品架构师" },
    { type: 'paragraph', text: "AI 不是来抢饭碗的，它是来“去噪”的。它去掉了对齐像素、切图、改文案这些由于工具限制而产生的“噪音”，让你不得不去面对设计最本质的问题：这个产品到底为谁解决问题？解决得够不够优雅？" }
  ];

  return (
    <ArticleTemplate 
      language={language}
      tag={isEn ? "AI Revolution" : "AI 变革"}
      date={isEn ? "Mar 05, 2024" : "2024年3月05日"}
      title={isEn ? "UX Revolution in AI Era: From Pixel Shifting to Logic Arrangement" : "AI 时代的 UX 变革：从“像素推移”到“逻辑编排”"}
      subtitle={isEn ? "Generative AI is shifting designer focus from the visual surface to the core product logic." : "生成式 AI 正在从底层改变我们构建数字产品的方式，将设计师的关注点拉升至“产品逻辑层”。"}
      sections={sections}
      onBack={onBack}
    />
  );
};

export default ArticleAIRevolution;
